/*Wounded sub-state enum*/
#define SUBSTATE_NONE  -1
#define SUBSTATE_FALL 0
#define SUBSTATE_INVH 1
#define SUBSTATE_DOWN 2
#define SUBSTATE_CRWL 3
#define SUBSTATE_HEAL 4
#define SUBSTATE_DRAG 5
#define SUBSTATE_CARR 6