//Target types
#define TARGET_TYPE_INF "INF"
#define TARGET_TYPE_VEH "VEH"
#define TARGET_TYPE_ARM "ARM"
#define TARGET_TYPE_AIR "AIR"
#define TARGET_TYPE_BOAT "BOAT"

//Statistics - Advanced Combat Active
#define STAT_ACA_AIRSTRIKE 0
#define STAT_ACA_ARTILLERY 1
#define STAT_ACA_VEH_DEMOL 2
#define STAT_ACA_INF_STORM 3
#define STAT_ACA_VEH_REPAIR 4
#define STAT_ACA_VEH_CAPTURE 5
#define STAT_ACA_VEH_FLEE 6

#define STAT_ACA_TOTAL 0
#define STAT_ACA_ABORTED 1
#define STAT_ACA_TIMEOUT 2
#define STAT_ACA_SUCCESS 3
